# Generated by Django 3.0 on 2022-08-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
