# Generated by Django 3.0 on 2022-08-08 15:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Imagen')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('titulo1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primer Titulo')),
                ('subtitulo1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primer Parrafo')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Adjunta la primera imagen')),
                ('titulo2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Titulo')),
                ('subtitulo2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Parrafo')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Adjunta la Segundo imagen')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='opening', verbose_name='Tercera Imagen')),
                ('titulo3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tercer Titulo')),
                ('subtitulo3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tercer parrafo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_equipos', to='about.Equipo')),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de Nosotros',
                'ordering': ['-created'],
            },
        ),
    ]
