# Generated by Django 3.0 on 2022-08-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='opening', verbose_name='Cuarta Imagen'),
        ),
    ]
