# Generated by Django 3.0 on 2022-08-08 16:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_imagen4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='subtitulo1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='Primer Parrafo'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitulo2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='Segundo Parrafo'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitulo3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200, null=True, verbose_name='Tercer parrafo'),
        ),
    ]
