# Generated by Django 3.0 on 2022-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='cantidad de visitas'),
        ),
    ]
